MotorClaims/Controllers/SurveyorController.cs
using CORE.DTOs.APIs.Business;
using CORE.DTOs.APIs.MotorClaim;
using CORE.DTOs.APIs.Process.Approvals;
using CORE.DTOs.APIs.TP_Services;
using CORE.DTOs.Authentications;
using CORE.DTOs.MotorClaim;
using CORE.DTOs.MotorClaim.Claims;
using CORE.DTOs.MotorClaim.Productions;
using CORE.DTOs.MotorClaim.WorkFlow;
using CORE.DTOs.Setups;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using MotorClaims.Models;
using System.Security.Claims;
using X.PagedList;
using static MotorClaims.Models.Enums;

namespace MotorClaims.Controllers
{
    public class SurveyorController : Controller
    {
        private static HttpClient client = new HttpClient();
        private readonly AppSettings _appSettings;
        private const string VehicleListCacheKey = "LookupTable";
        private readonly IMemoryCache _memoryCache;
        public static IWebHostEnvironment _environment;
        List<LookupTable> query = new List<LookupTable>();

        public SurveyorController(IOptions<AppSettings> appSettings, IWebHostEnvironment environment, IMemoryCache memoryCache)
        {
            _environment = environment;
            _appSettings = appSettings.Value;
            _memoryCache = memoryCache;
            _memoryCache.TryGetValue(VehicleListCacheKey, out query);
        }

        public IActionResult Index(int page=1)
        {
            List<ClaimMaster> claim = new List<ClaimMaster>();
            claim = HttpContext.Session.getSessionData<List<ClaimMaster>>("SearchResult");
            IPagedList<ClaimMaster> claims = claim.ToPagedList(page, _appSettings.PageSize);
            ViewData["searchObj"] = new SearchObj();
            ViewData["AllUsers"] = HttpContext.Session.getSessionData<List<Users>>("AllUsers");
            return View(claims);
        }

        public IActionResult SurveyorEntry(string obj)
        {
            ClaimSearchobj claimSearchobj = Helpers.Deserilize<ClaimSearchobj>(Helpers.Decryption(obj));
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                Id = Convert.ToInt32(claimSearchobj.ClaimId)

            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaimsMaster,
                Request = mainSearchMC
            };
            var claim = Helpers.ExcutePostAPI<List<ClaimMaster>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");
            ViewData["query"] = query;
            ViewData["DocumentsLink"]= _appSettings.DocumentsLink;


            return View(claim.FirstOrDefault());
        }

        [HttpPost]
        public IActionResult SearchSurveyors(SearchObj searchObj)
        {
            if (string.IsNullOrEmpty(searchObj.nationalid) && !searchObj.RegisteredFrom.HasValue && !searchObj.RegisteredTo.HasValue && string.IsNullOrEmpty(searchObj.chassis) && string.IsNullOrEmpty(searchObj.claimno) && string.IsNullOrEmpty(searchObj.mobile) && string.IsNullOrEmpty(searchObj.policy))
            {
                return RedirectToAction("Index", new { err = "Please fill at least one parameter" });
            }
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                NationalID = searchObj.nationalid,
                chassis = searchObj.chassis,
                claimno = searchObj.claimno,
                mobile = searchObj.mobile,
                policy = searchObj.policy,
                RegisteredFrom = searchObj.RegisteredFrom,
                RegisteredTo = searchObj.RegisteredTo,
                ClaimStatus = (int)Enums.ClaimantStatus.Operation

            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaimsMaster,
                Request = mainSearchMC
            };
            var claim = Helpers.ExcutePostAPI<List<ClaimMaster>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");

            IPagedList<ClaimMaster> Surveyors = claim.ToPagedList(1, _appSettings.PageSize);
            HttpContext.Session.SetSessionData("SearchResult", claim);
            ViewData["searchObj"] = searchObj;
            ViewData["AllUsers"] = HttpContext.Session.getSessionData<List<Users>>("AllUsers");
            return View("Index", Surveyors);
        }

        [HttpPost]
        public IActionResult InsertSurveyor(Survoyer survoyer)
        {
            string obj = HttpContext.Request.Form["claimSearchobj"].ToString();
            survoyer.CreationDate = DateTime.Now;
            survoyer.CreatedBy = HttpContext.Session.getSessionData<Users>("LoggedUser").UserName;
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.InsertUpdateSurvoyerEntry,
                Request = survoyer
            };
            survoyer = Helpers.ExcutePostAPI<Survoyer>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                ClaimantId=survoyer.ClaimantId,
                TransactionType=(int)Enums.ClaimTransactionTypes.Reserve
            };
             setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaimTransactions,
                Request = mainSearchMC
            };
            var Reserve = Helpers.ExcutePostAPI<List<ClaimTransactions>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");


            decimal OS = 0,Diff=Convert.ToDecimal( survoyer.EstimatedSPAmount+survoyer.EstimatedLabourAmount);
            foreach (var item in Reserve)
            {
                OS += item.TransactionAmount;
            }
            ClaimTransactions claimTransactions = new ClaimTransactions()
            {
                ClaimantID = survoyer.ClaimantId,
                ClaimId = survoyer.ClaimId,
                CreatedBy = HttpContext.Session.getSessionData<Users>("LoggedUser").UserName,
                isActive = true,
                TransactionAmount =  Diff-OS,
                TransactionDate = DateTime.Now,
                TransactionType = (int)Enums.ClaimTransactionTypes.Reserve,
                Note = survoyer.Note,
            };
            setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.InsertUpdateClaimTransaction,
                Request = claimTransactions
            };
            claimTransactions = Helpers.ExcutePostAPI<ClaimTransactions>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");

            Helpers.RegisterHistory(_appSettings, survoyer.ClaimId, "Update Claim Reserve to " + Diff, HttpContext.Session.getSessionData<Users>("LoggedUser").UserName, 1);

            return RedirectToAction("SurveyorEntry",new { obj = obj });
        }

        [HttpPost]
        public async void UploadAttachments(int Id, int ClaimId,int ClaimantId, int ModuleId, IList<IFormFile> files)
        {

            if (files != null && files.Count > 0)
            {
                Attachments attachment = new Attachments()
                {
                    ClaimantId = ClaimantId,
                    ClaimId = ClaimId,
                    CreationDate = DateTime.Now,
                    DocumentSetupId = Id,
                    ModuleId = ModuleId,
                    FileName = Path.GetFileName(files[0].FileName),
                    ContentType = files[0].ContentType,
                    CreatedBy = "Test",
                    IsDeleted = false,
                };
                SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
                {
                    TransactionType = CORE.Extensions.ClaimTransactionType.InsertUpdateAttachment,
                    Request = attachment
                };
                attachment = Helpers.ExcutePostAPI<Attachments>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");

                foreach (IFormFile file in files)
                {
                    string pathMDF = _appSettings.ExcelPath;
                    string fieNameWithExt = attachment.Id.ToString() + "_" + Path.GetFileName(file.FileName);
                    System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
                    if (file.Length > 0)
                    {
                        string directory = Path.Combine(pathMDF, attachment.ClaimantId.ToString());
                        bool folderExists = Directory.Exists(directory);
                        if (!folderExists)
                            Directory.CreateDirectory(directory);

                        string filePath = Path.Combine(directory, fieNameWithExt);
                        using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                        }
                    }
                }

            }

        }

        public IActionResult SurveyorAssign(int ClaimId,int ClaimantId)
        {
            ViewData["DivName"] = "SurveyorAssign";
            ViewData["AllUsers"] = HttpContext.Session.getSessionData<List<Users>>("AllUsers");
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                Id = ClaimId,
                ClaimantId= ClaimantId
            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {

MotorClaims/Views/Surveyor/SurveyorActions.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http.Features
@using System.Globalization

@inject IViewLocalizer _localizer
@using CORE.DTOs.MotorClaim.Claims;


@{
    Layout = null;
}
@model ClaimMaster

<form method="post" asp-action="UpdateClaimantActions" asp-controller="Surveyor">

    <input type="hidden" name="Id" value="@Model.claims.Id"/>
    <input type="hidden" id="hfSurveyorActions" name="hfSurveyorActions"/>

    <div class="slide-popup-inner">
        <div class="slide-header">
            <div class="heading-card">
                <h2 class="heading">
                    @_localizer["SurveyorActions"].Value
                    
                </h2>
            </div>
        </div>
        <div class="slide-body">
            <div class="popup-body-wrapper">
                <div class="body-content-wrapper">
                    <div class="delete-content-card">
                        <div class="body-delete-header">
                            <h2 class="heading-title">@Model.claims.ClaimNo</h2>
                            <span class="active-employee">
                                @_localizer["Employee"].Value
                                
                            </span>
                        </div>
                        <ul class="list-detail">
                            <li class="list-item-delete">
                                <span class="label">
                                    @_localizer["OwnerName:"].Value
                                    
                                </span>
                                <span class="value">@Model.claims.Owner</span>
                            </li>
                            <li class="list-item-delete">
                                <span class="label">
                                    @_localizer["PolicyNo:"].Value
                                    
                                </span>
                                <span class="value">@Model.claims.PolicyNo</span>
                            </li>
                            <li class="list-item-delete">
                                <span class="label">
                                    @_localizer["PlateNo:"].Value
                                    
                                </span>
                                <span class="value">@Model.claims.PlateNo</span>
                            </li>
                            <li class="list-item-delete">
                                <span class="label">
                                    @_localizer["FraudScore:"].Value
                                    
                                </span>
                                <span class="value">@Model.claims.FraudScore</span>
                            </li>
                        </ul>
                              <div class="cancel-declaration">
                            <h3 class="title-label">
                                @_localizer["Claimant"].Value
                                
                            </h3>
                            <div class="form-field-wrapper">
                                <div class="form-input-wrapper">
                                    <select class="form-inputbox" required name="ClaimantId">
                                      <option value="@Model.claimants.Id">@Model.claimants.ClaimantName</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="cancel-declaration">
                            <h3 class="title-label">
                                @_localizer["Action"].Value
                                
                            </h3>
                            <div class="form-field-wrapper">
                                <div class="form-input-wrapper">
                                    <select class="form-inputbox" required id="ddlSurveyorActions" name="SurveyorActions">
                                        <option value=""></option>
                                        <option value="1">
                                            @_localizer["PendingforSurveyor"].Value
                                            
                                        </option>
                                        <option value="2">
                                            @_localizer["Waitingestimations"].Value
                                            
                                        </option>
                                        <option value="3">
                                            @_localizer["Senttoserviceunit"].Value
                                            
                                        </option>
                                        <option value="4">
                                            @_localizer["WaitingCustomertodeliverhisvehicle"].Value
                                            
                                        </option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="slide-footer">
                    <div class="slide-inner-footer">
                        <button type="button" class="button button-secondary-border"
                                onclick="CloseDialogV('SurveyorActions')">
                            @_localizer["Cancel"].Value
                            
                        </button>
                        <button type="submit" class="button button-primary">
                            @_localizer["Update"].Value
                            
                        </button>
                    </div>
                </div>
            </div>
        </div>


    </div>

</form>

<script>
    $(function(){
        $('#ddlSurveyorActions').on('change', function() {
 $('#hfSurveyorActions').val($( "#ddlSurveyorActions option:selected" ).text());
});
    });
</script>

MotorClaims/Views/Surveyor/SurveyorEntry.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http.Features
@using System.Globalization

@inject IViewLocalizer _localizer
@using CORE.DTOs.MotorClaim.Claims;
@using Newtonsoft.Json;

@model ClaimMaster
@{
    List<LookupTable> lookupTables = (List<LookupTable>)ViewData["query"];
        string DocumentsLink=(string)ViewData["DocumentsLink"];
    await Html.RenderPartialAsync("_PolicyInfo",Model.productionInfo);
    await Html.RenderPartialAsync("_VehicleInfo", Model.vehiclesInfo);
    await Html.RenderPartialAsync("_ClaimInfo", Model.claims);
    await Html.RenderPartialAsync("_ClaimantInfo",new { Model = Model.claimants,Lookups = lookupTables});
    await Html.RenderPartialAsync("_DocumentsInfo",new { Model = Model.attachments, Link = DocumentsLink,ClaimNo=string.Concat(Model.claims.ClaimNo,"/",Model.claimants.Serial),Documents=Model.documentInfos});

}

<div class="transaction-details">
    <table class="universal-table">
        <tr>
            <!-- <th>#</th> -->
            <th>
                @_localizer["ClaimantType"].Value
                
            </th>
            <th>
                @_localizer["ClaimantName"].Value
                
            </th>
            <th>
                @_localizer["NatureofLoss"].Value
                
            </th>
            <th>
                @_localizer["Make"].Value
                
            </th>
            <th>
                @_localizer["Model"].Value
                
            </th>
            <th>
                @_localizer["Chassis"].Value
                
            </th>
            <th>
                @_localizer["PlateNo"].Value
                
            </th>
            <th>
                @_localizer["ClaimantStatus"].Value
                
            </th>

        </tr>



            <tr>
                @{
                 ClaimSearchobj   claimSearchobj = new ClaimSearchobj()
                {
                    PolicyId = Model.productionInfo.Id,
                    VehicleId = Model.vehiclesInfo.Id,
                    ClaimId = Model.claimants.ClaimId,
                    ClaimantId = Model.claimants.Id,
                    
                };
                    string ClaimantType = lookupTables.Where(p => p.Code == Model.claimants.ClaimantType.Value.ToString() && p.MajorCode==(int)Enums.Lookups.ClaimantType).FirstOrDefault().NameEnglish;
                    string ClaimantResult = lookupTables.Where(p => p.Code == Model.claimants.NatureofLoss.Value.ToString() && p.MajorCode==(int)Enums.Lookups.CauseOfLoss).FirstOrDefault().NameEnglish;
                }
                <td class="tran"><a onclick="LoadSurveyorList('@MotorClaims.Models.Helpers.Encrypt(JsonConvert.SerializeObject(claimSearchobj))')">#@ClaimantType</a></td>
                <td>@Model.claimants.ClaimantName</td>
                <td>@ClaimantResult</td>
                <td>@Model.claimants.MakeDesc</td>
                <td>@Model.claimants.ModelDesc</td>
                <td>@Model.claimants.ChassisNo</td>
                <td>@Model.claimants.PlateNo</td>
                <td>@(((Enums.ClaimantStatus)Model.claimants.ClaimantStatus).ToString())</td>

            </tr>


        
    </table>
</div>


<div id="SurveyorEntry"></div>


<script>

    function LoadSurveyorList(Id){
        $('#SurveyorEntry').load('/Surveyor/LoadSurveyorsList/',{Id:Id});
    }

      function LoadSurveyorEntry(Id){
        $('#SurveyorEntry').load('/Surveyor/LoadSurveyorEntry/',{Id:Id});
    }  
    
    function LoadSurveyorMissing(Id){
        $('#SurveyorEntry').load('/Surveyor/LoadSurveyorMissing/',{Id:Id});
    }
</script>