MotorClaims/Controllers/ApprovalsController.cs
using CORE.DTOs.MotorClaim.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using MotorClaims.Models;

namespace MotorClaims.Controllers
{
    public class ApprovalsController : Controller
    {
        private static HttpClient client = new HttpClient();
        private readonly AppSettings _appSettings;
        private const string VehicleListCacheKey = "ServicesLink";
        private readonly IMemoryCache _memoryCache;
        public static IWebHostEnvironment _environment;
        CORE.DTOs.APIs.TP_Services.APIsLists query = new CORE.DTOs.APIs.TP_Services.APIsLists();

        public ApprovalsController(IOptions<AppSettings> appSettings, IWebHostEnvironment environment, IMemoryCache memoryCache)
        {
            _environment = environment;
            _appSettings = appSettings.Value;
            _memoryCache = memoryCache;
            _memoryCache.TryGetValue(VehicleListCacheKey, out query);
        }
        public IActionResult Index()
        {
            return View(new List<Claims>());
        }
    }
}

MotorClaims/Controllers/SearchController.cs
using CORE.DTOs.APIs.Business;
using CORE.DTOs.APIs.MotorClaim;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using MotorClaims.Models;
using Newtonsoft.Json;

namespace MotorClaims.Controllers
{
    public class SearchController : Controller
    {
        private static HttpClient client = new HttpClient();
        private readonly AppSettings _appSettings;
        private const string VehicleListCacheKey = "ServicesLink";
        private readonly IMemoryCache _memoryCache;
        public static IWebHostEnvironment _environment;
        CORE.DTOs.APIs.TP_Services.APIsLists query = new CORE.DTOs.APIs.TP_Services.APIsLists();
        public SearchController(IOptions<AppSettings> appSettings, IWebHostEnvironment environment, IMemoryCache memoryCache)
        {
            _environment = environment;
            _appSettings = appSettings.Value;
            _memoryCache = memoryCache;
            _memoryCache.TryGetValue(VehicleListCacheKey, out query);
        }
        public IActionResult Index()
        {
            ViewData["search"] = new Search();
            return View();
        }

        [HttpPost]
        public IActionResult Search(Search search)
        {
            SearchingObj searchingObj = new SearchingObj()
            {
                ChassisNo = search.chassis,
                ClaimNo = search.claimno,
                ComplainNo = search.complain,
                CustomNo = search.custom,
                MobileNo = search.mobile,
                NationalId = search.nationalid,
                PlateNo = search.plate,
                PolicyNo = search.policy,
                SequenceNo = search.sequence,
            };
            ClaimSearchResult claimSearchResult = new ClaimSearchResult();
            ViewData["search"] = search;
            if (string.IsNullOrEmpty(search.chassis) && string.IsNullOrEmpty(search.claimno) && string.IsNullOrEmpty(search.complain) 
                && string.IsNullOrEmpty(search.custom) && string.IsNullOrEmpty(search.mobile) && string.IsNullOrEmpty(search.nationalid)
                && string.IsNullOrEmpty(search.plate) && string.IsNullOrEmpty(search.policy) && string.IsNullOrEmpty(search.sequence))
            {
                ViewData["Error"] = "Fill at least one parameter";
                return View("Index", claimSearchResult);
            }
        
            claimSearchResult = Helpers.ExcutePostAPI<ClaimSearchResult>(searchingObj, _appSettings.APIHubPrefix + "api/MotorClaim/SearchClaimInfo");
            //claimSearchResult = JsonConvert.DeserializeObject<ClaimSearchResult>(JsonConvert.SerializeObject(obj));
        
            HttpContext.Session.SetSessionData("SearchResult", claimSearchResult);
            return View("Index", claimSearchResult);
        }
    }
}

MotorClaims/Controllers/SetupController.cs
using CORE.DTOs.APIs.MotorClaim;
using CORE.DTOs.MotorClaim.Claims;
using CORE.DTOs.MotorClaim.WorkFlow;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using MotorClaims.Models;

namespace MotorClaims.Controllers
{
    public class SetupController : Controller
    {
        private static HttpClient client = new HttpClient();
        private readonly AppSettings _appSettings;
        private const string VehicleListCacheKey = "ServicesLink";
        private readonly IMemoryCache _memoryCache;
        public static IWebHostEnvironment _environment;
        CORE.DTOs.APIs.TP_Services.APIsLists query = new CORE.DTOs.APIs.TP_Services.APIsLists();
        public SetupController(IOptions<AppSettings> appSettings, IWebHostEnvironment environment, IMemoryCache memoryCache)
        {
            _environment = environment;
            _appSettings = appSettings.Value;
            _memoryCache = memoryCache;
            _memoryCache.TryGetValue(VehicleListCacheKey, out query);
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Authority(string err = null, int? Status = null)
        {

                ViewData["Error"] = err;
                ViewData["Filter"] = Status;
                MainSearchMC mainSearchMC = new MainSearchMC();
                SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
                {
                    TransactionType = CORE.Extensions.ClaimTransactionType.LoadAuthorityMatrix,
                    Request = mainSearchMC
                };
                var AuthorityMatrix = Helpers.ExcutePostAPI<List<AuthorityMatrix>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");
                ViewData["AuthorityMatrix"] = AuthorityMatrix;
                return View();
        }


        public IActionResult UpdateAuthority(int Id)
        {
            if (Id > 0)
            {
                MainSearchMC mainSearchMC = new MainSearchMC()
                {
                    Id = Id
                };
                SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
                {
                    TransactionType = CORE.Extensions.ClaimTransactionType.LoadAuthorityMatrix,
                    Request = mainSearchMC
                };
                var Documents = Helpers.ExcutePostAPI<List<AuthorityMatrix>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");

                return View(Documents.FirstOrDefault());
            }
            return View(new AuthorityMatrix());

        }

        [HttpPost]
        public IActionResult UpdateAuthority(AuthorityMatrix Authority)
        {
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.InsertUpdateDocuments,
                Request = Authority
            };
            var documents = Helpers.ExcutePostAPI<AuthorityMatrix>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");

            return RedirectToAction("Authority");
        }

        [HttpPost]
        public IActionResult SearchAuthorities()
        {
            int? Status = null;
            try
            {
                Status = Convert.ToInt32(HttpContext.Request.Form["Filter"]);
            }
            catch (Exception)
            {
            }


            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                ModuleId = Status
            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadAuthorityMatrix,
                Request = mainSearchMC
            };
            var Documents = Helpers.ExcutePostAPI<List<AuthorityMatrix>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");
            ViewData["AuthorityMatrix"] = Documents;
            ViewData["Error"] = null;
            ViewData["Filter"] = Status;
            return View("Authority");
        }


        public IActionResult Reports()
        {
            return View();
        }
    }
}

MotorClaims/Controllers/WorkFlowController.cs
using CORE.DTOs.APIs.MotorClaim;
using CORE.DTOs.MotorClaim.WorkFlow;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using MotorClaims.Models;

namespace MotorClaims.Controllers
{
    public class WorkFlowController : Controller
    {
        private static HttpClient client = new HttpClient();
        private readonly AppSettings _appSettings;
        private const string VehicleListCacheKey = "ServicesLink";
        private readonly IMemoryCache _memoryCache;
        public static IWebHostEnvironment _environment;
        CORE.DTOs.APIs.TP_Services.APIsLists query = new CORE.DTOs.APIs.TP_Services.APIsLists();
        public WorkFlowController(IOptions<AppSettings> appSettings, IWebHostEnvironment environment, IMemoryCache memoryCache)
        {
            _environment = environment;
            _appSettings = appSettings.Value;
            _memoryCache = memoryCache;
            _memoryCache.TryGetValue(VehicleListCacheKey, out query);
        }
        public IActionResult Index(string err = null, string? Status = null)
        {
            ViewData["Error"] = err;
            ViewData["Filter"] = Status;
            MainSearchMC mainSearchMC = new MainSearchMC();
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadWorkFlowStage,
                Request = mainSearchMC
            };
            var WF = Helpers.ExcutePostAPI<List<WorkFlowStages>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");
            ViewData["WF"] = WF;
            return View();
        }

        public IActionResult UpdateWorkFlow(int Id)
        {
            if (Id > 0)
            {
                MainSearchMC mainSearchMC = new MainSearchMC()
                {
                    Id = Id
                };
                SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
                {
                    TransactionType = CORE.Extensions.ClaimTransactionType.LoadWorkFlowStage,
                    Request = mainSearchMC
                };
                var WF = Helpers.ExcutePostAPI<List<WorkFlowStages>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");

                return View(WF.FirstOrDefault());
            }

            return View(new WorkFlowStages());
        }

        [HttpPost]
        public IActionResult UpdateWorkFlow(WorkFlowStages workFlowStages)
        {

            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.InsertUpdateWorkFlowStage,
                Request = workFlowStages
            };
            var WF = Helpers.ExcutePostAPI<WorkFlowStages>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");

            return RedirectToAction("Index");
        }
        public IActionResult UpdateWorkFlowApproversV(int Id)
        {

            ViewData["WFId"] = Id;
            return View("UpdateWorkFlowApprovers",new WorkFlowApprovers());
        }


        [HttpPost]
        public IActionResult UpdateWorkFlowApprovers(WorkFlowApprovers workFlowApprovers)
        {

            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.InsertWorkFlowApprovers,
                Request = workFlowApprovers
            };
            workFlowApprovers = Helpers.ExcutePostAPI<WorkFlowApprovers>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult SearchWorkFlow()
        {
            string? Status = HttpContext.Request.Form["Filter"];

            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                Name = Status
            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadWorkFlowStage,
                Request = mainSearchMC
            };
            var WF = Helpers.ExcutePostAPI<List<WorkFlowStages>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");
            ViewData["WF"] = WF;
            ViewData["Error"] = null;
            ViewData["Filter"] = Status;
            return View("Index");
        }

        public IActionResult LoadWorkFlowApprovers(int Id)
        {
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                WorkFlowId = Id
            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadWorkFlowApprovers,
                Request = mainSearchMC
            };
            var approvers = Helpers.ExcutePostAPI<List<WorkFlowApprovers>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");

            return View(approvers);
        }
        public IActionResult DeleteApprover(int Id)
        {
            ViewData["Controller"] = "Workflow";
            ViewData["Action"] = "DeleteApproverPost";

            return View("_DeleteConfirmation", Id);
        }
        [HttpPost]
        public IActionResult DeleteApproverPost(int Id)
        {
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                Id = Id
            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.DeleteWorkFlowApprovers,
                Request = mainSearchMC
            };
            var Delegations = Helpers.ExcutePostAPI<bool>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/SetupMotorClaim");

            return RedirectToAction("Index");
        }
    }
}

MotorClaims/Views/Shared/_ContentSection.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http.Features
@using System.Globalization

@inject IViewLocalizer _localizer
<div class="policy-wrapper">
    <h2 class="heading">
        @_localizer["SytemSetup"].Value
    </h2>
    <div class="policy-carousel-wrapper">
        <a href="@Url.Action("Index","Delegation")" class="policy-card cursor-pointer" >

            <div class="policy-internal-wrapper" id="shad1">
                <div class="policy-card-header">
                    <div class="policy-type-icon">
                        <img src="/assets/icons/delegation.png" width="50" />
                    </div>
                </div>
                <div class="policy-card-body">
                    <h3 class="policy-name">
                        @_localizer["Delegation"].Value
                    </h3>
                </div>

            </div>
    
        </a>
        <a href="@Url.Action("Index","WorkFlow")" class="policy-card cursor-pointer" >

            <div class="policy-internal-wrapper" id="shad2">
                <div class="policy-card-header">
                    <div class="policy-type-icon">
                        <img src="/assets/icons/WorkFlow.png" width="50" />
                    </div>
                </div>
                <div class="policy-card-body">
                    <h3 class="policy-name">
                        @_localizer["WorkFlow"].Value
                    </h3>
                </div>

       
        </div>
        </a>
        <a href="@Url.Action("Index","Documents")" class="policy-card cursor-pointer" >

            <div class="policy-internal-wrapper" id="shad3">
                <div class="policy-card-header">
                    <div class="policy-type-icon">
                        <img src="/assets/icons/Documents.png" width="50" />
                    </div>

                </div>
                <div class="policy-card-body">
                    <h3 class="policy-name">
                        @_localizer["Documents"].Value
                    </h3>
                </div>

       
        </div>
        </a>
        <a href="@Url.Action("Index","Fraud")" class="policy-card cursor-pointer" >

            <div class="policy-internal-wrapper" id="shad4">
                <div class="policy-card-header">
                    <div class="policy-type-icon">
                        <img src="/assets/icons/Fraud.png" width="50" />
                    </div>

                </div>
                <div class="policy-card-body">
                    <h3 class="policy-name">
                        @_localizer["Fraud"].Value
                    </h3>
                </div>

            </div>
  
        </a>
        <a href="@Url.Action("Index","Access")" class="policy-card cursor-pointer">
  
            <div class="policy-internal-wrapper" id="shad5">
                <div class="policy-card-header">
                    <div class="policy-type-icon">
                        <img src="/assets/icons/Access.png" width="50" />
                    </div>

                </div>
                <div class="policy-card-body">
                    <h3 class="policy-name">
                        @_localizer["Access"].Value
                    </h3>
                </div>

            </div>

        </a>    
        
        <a href="@Url.Action("Authority","Setup")" class="policy-card cursor-pointer">
  
            <div class="policy-internal-wrapper" id="shad6">
                <div class="policy-card-header">
                    <div class="policy-type-icon">
                        <img src="/assets/icons/Authority.png" width="50" />
                    </div>

                </div>
                <div class="policy-card-body">
                    <h3 class="policy-name">
                        @_localizer["Authority"].Value
                    </h3>
                </div>

            </div>

        </a>
    </div>
</div>

MotorClaims/Views/Shared/_LayoutDashboard.cshtml
@using CORE.DTOs.APIs.Authenticator;
@using CORE.DTOs.Authentications;
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http.Features
@using System.Globalization
@using MotorClaims.Models
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    LoginObj users = new LoginObj();
    users = Context.Session.getSessionData<LoginObj>("loginObj");

}

@inject IViewLocalizer _localizer
@inject IOptions<RequestLocalizationOptions> locOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = locOptions.Value.SupportedCultures.Select(c => new SelectListItem(value: c.Name, text: c.DisplayName)).ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        @_localizer["Document"].Value
        
    </title>

    <link href="~/styles/commonStyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/styles/layout/layout.css" />
    <link rel="stylesheet" href="~/styles/policyStyle/policyTiles.css">
    <link href="~/styles/creditLimit/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/styles/dashboard/dasbboard.css" />
    <link href="~/styles/header/header.css" rel="stylesheet" />
    <link href="~/styles/languageStyle/languageStyle.css" rel="stylesheet" />
    <link href="~/styles/Pagination.css" rel="stylesheet" />
    <link href="~/styles/add-member/add-member.css" rel="stylesheet" />
    <script src="~/assets/Content/Js/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="~/assets/Content/Js/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/assets/Content/Js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="~/styles/request/request.css" />
    <link rel="stylesheet" href="~/styles/Spinner.css" />
    <script src="~/assets/Content/Login/jquery.toast.js" type="text/javascript"></script>
    <script src="~/assets/Content/Login/Login.js" type="text/javascript"></script>
    <link href="~/assets/Content/Login/jquery.toast.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/styles/policydetail/policyDetailHeader.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="~/styles/policydetail/policyDetailHeader.css">

</head>

<body>
    <main class="main-layout">

        <div class="sidebar-wrapper">
            <aside class="sidebar">
                <div class="sidebar-logo-wrapper">
                    <img class="logo" src="~/assets/icons/AJT1.png" />
                </div>
                <nav class="navigation-wrapper">
                    <ul class="naigation-list">
                        @*   @if ((int)MotorClaims.Models.Enums.Roles.Admin == users?.Roles?.Id || (int)MotorClaims.Models.Enums.Roles.Sales == users?.Roles?.Id || (int)MotorClaims.Models.Enums.Roles.Broker == users?.Roles?.Id || (int)MotorClaims.Models.Enums.Roles.Agent == users?.Roles?.Id)
                        {*@
                             @if ((int)MotorClaims.Models.Enums.Roles.Sales == users.Roles.Id || (int)MotorClaims.Models.Enums.Roles.Agent == users.Roles.Id || (int)MotorClaims.Models.Enums.Roles.Broker == users.Roles.Id || (int)MotorClaims.Models.Enums.Roles.Admin == users.Roles.Id)
                        {
                            <li class="navigation-item">

                                <a class="menu-item-wrapper active" title="Home" href="@Url.Action("Index","Home")">
                                    <img src="~/assets/icons/sidebar/home.svg" class="menu-icon" />
                                </a>
                            </li>
                        }
                        @*  }*@

                        <li class="navigation-item">
                            <a class="menu-item-wrapper" href="@Url.Action("Index","Search")" title="@_localizer["UWApprovals"]" aria-current="page">
                                <img src="~/assets/icons/search.svg" class="menu-icon" />
                            </a>
                        </li>

                        <li class="navigation-item">
                            <a class="menu-item-wrapper" href="@Url.Action("ApprovalsHistory","Approvals")" title="@_localizer["ApprovalsHistory"]" aria-current="page">
                                <img src="~/assets/icons/sidebar/help.svg" class="menu-icon" />
                            </a>
                        </li>
                        @if ((int)MotorClaims.Models.Enums.Roles.Approval == users.Roles.Id || (int)MotorClaims.Models.Enums.Roles.Admin == users.Roles.Id)
                        {
                            <li class="navigation-item">
                                <a class="menu-item-wrapper" href="@Url.Action("Approvals","Approvals")" title="@_localizer["MyApprovals"]" aria-current="page">
                                    <img src="~/assets/icons/sidebar/Complaints.svg" class="menu-icon" />
                                </a>
                            </li>


                        }
                        @if ((int)MotorClaims.Models.Enums.Roles.Finance == users.Roles.Id || (int)MotorClaims.Models.Enums.Roles.Admin == users.Roles.Id)
                        {
                            <li class="navigation-item">
                                <a class="menu-item-wrapper" href="@Url.Action("FinanceApprovals","Approvals")" title="@_localizer["FinanceApprovals"]" aria-current="page">
                                    <img src="~/assets/icons/sidebar/Complaints.svg" class="menu-icon" />
                                </a>
                            </li>
                            <li class="navigation-item">
                                <a class="menu-item-wrapper" href="@Url.Action("CreditLimit","Managing")" title="@_localizer["CreditMoney"]" aria-current="page">
                                    <img src="~/assets/icons/Money.png" class="menu-icon" />
                                </a>
                            </li>
                        }
                        @if ((int)MotorClaims.Models.Enums.Roles.Sales == users.Roles.Id || (int)MotorClaims.Models.Enums.Roles.Agent == users.Roles.Id || (int)MotorClaims.Models.Enums.Roles.Broker == users.Roles.Id || (int)MotorClaims.Models.Enums.Roles.Admin == users.Roles.Id)
                        {
                            <li class="navigation-item">
                                <a class="menu-item-wrapper" href="@Url.Action("TeamLead","Approvals")" title="@_localizer["TeamLeadPage"]" aria-current="page">
                                    <img src="~/assets/icons/sidebar/Complaints.svg" class="menu-icon" />
                                </a>
                            </li>
                        }
                        @if ((int)MotorClaims.Models.Enums.Roles.IT == users.Roles.Id  || (int)MotorClaims.Models.Enums.Roles.Admin == users.Roles.Id)
                        {
                            <li class="navigation-item">
                                <a class="menu-item-wrapper" href="@Url.Action("Index","Managing")" title="@_localizer["ManageUsers"]" aria-current="page">
                                    <img src="~/assets/icons/sidebar/Complaints.svg" class="menu-icon" />
                                </a>
                            </li>
                        }
                    </ul>
                </nav>
            </aside>
        </div>

        <div class="header-logedin">
            @*  <div class="breadcrumb">

            @_localizer["Dashboard"].Value

            </div>*@
            <div class="static-header">
                <ul class="static-menu-list">
                    <li class="static-item-header">
                        <div class="lang cursor-pointer" onclick="handleLanguagePopup()">
                            <p>@_localizer["LNG"].Value</p>
                            <img src="~/assets/icons/world.svg" alt="world" class="language" />
                            <img src="~/assets/icons/chevron-down.svg" class="language-drop-icon" alt="">


                            @{
                                await Html.RenderPartialAsync("_SelectLanguagePartial");
                            }
                        </div>
                    </li>
                    <li class="profile">
                        <img src="~/assets/icons/user.svg" style="cursor:pointer" onclick="OpenLogout()">
                    </li>
                </ul>
            </div>
        </div>
        <div class="content-wrapper">
            @RenderBody()
        </div>
    </main>
    <img id="spinner" src="~/assets/icons/Spinner.svg" />
</body>

<script src="~/scripts/language.js"></script>
<script src="~/scripts/membersAccordion.js"></script>
<script src="~/scripts/popupScript.js"></script>
<script src="~/scripts/idTypes.js"></script>

<script src="~/scripts/multiselect.js"></script>

@RenderSection("scripts", required: false)
</html>

<div id="delete-summary-modal2" class="delete-dependent-modal">
    <form asp-controller="Home" asp-action="Logout" method="post">
        <div class="modal-content">
            <div class="modal-header">
                <span class="close-delete-dependent" onclick="Close('delete-summary-modal2')">&times;</span>
                <h2>@_localizer["Logout"].Value</h2>
            </div>
            <div class="modal-body">
                <p class="delete-text">
                    @_localizer["Are"].Value
                </p>
            </div>
            <div class="modal-footer">
                <button onclick="Close('delete-summary-modal2')" type="button" class="button button-secondary-border">@_localizer["Cancel"].Value</button>
                <button class="button button-primary" type="submit">@_localizer["OK"].Value</button>
            </div>
        </div>
    </form>
</div>