MotorClaims/Controllers/OperationsController.cs
using CORE.DTOs.APIs.MotorClaim;
using CORE.DTOs.APIs.TP_Services;
using CORE.DTOs.Authentications;
using CORE.DTOs.MotorClaim;
using CORE.DTOs.MotorClaim.Claims;
using CORE.DTOs.Setups;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using MotorClaims.Models;
using System.Security.Claims;
using X.PagedList;

namespace MotorClaims.Controllers
{
    public class OperationsController : Controller
    {
        private static HttpClient client = new HttpClient();
        private readonly AppSettings _appSettings;
        private const string VehicleListCacheKey = "LookupTable";
        private readonly IMemoryCache _memoryCache;
        public static IWebHostEnvironment _environment;
        List<LookupTable> query = new List<LookupTable>();

        public OperationsController(IOptions<AppSettings> appSettings, IWebHostEnvironment environment, IMemoryCache memoryCache)
        {
            _environment = environment;
            _appSettings = appSettings.Value;
            _memoryCache = memoryCache;
            _memoryCache.TryGetValue(VehicleListCacheKey, out query);
        }
        public IActionResult Index(int page=1,string? err=null)
        {
            ViewData["searchObj"] = new SearchObj();
            ViewData["Error"] = err;
            List<ClaimMaster> claim = new List<ClaimMaster>();
            claim = HttpContext.Session.getSessionData<List<ClaimMaster>>("ClaimMaster");
            ViewData["AllUsers"] = HttpContext.Session.getSessionData<List<Users>>("AllUsers");
            IPagedList<ClaimMaster> claims = claim.ToPagedList(page, _appSettings.PageSize);
            return View(claims);
        }
        [HttpPost]
        public IActionResult SearchOperations(SearchObj searchObj)
        {
            List<ClaimMaster> claim = new List<ClaimMaster>();
            IPagedList<ClaimMaster> Operations= claim.ToPagedList(1, _appSettings.PageSize);
            ViewData["searchObj"] = searchObj;
            ViewData["AllUsers"] = HttpContext.Session.getSessionData<List<Users>>("AllUsers");
            if (string.IsNullOrEmpty(searchObj.nationalid) && !searchObj.RegisteredFrom.HasValue && !searchObj.RegisteredTo.HasValue  && string.IsNullOrEmpty(searchObj.chassis) && string.IsNullOrEmpty(searchObj.claimno) && string.IsNullOrEmpty(searchObj.mobile) && string.IsNullOrEmpty(searchObj.policy))
            {
                return RedirectToAction("Index",new {err= "Please fill at least one parameter" } );
            }
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                NationalID = searchObj.nationalid,
                chassis = searchObj.chassis,
                claimno = searchObj.claimno,
                mobile = searchObj.mobile,
                policy = searchObj.policy,
                RegisteredFrom = searchObj.RegisteredFrom,
                RegisteredTo = searchObj.RegisteredTo,
                ClaimStatus = (int)Enums.ClaimantStatus.Operation

            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaimsMaster,
                Request = mainSearchMC
            };
             claim = Helpers.ExcutePostAPI<List<ClaimMaster>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");
         
            HttpContext.Session.SetSessionData("ClaimMaster", claim);
             Operations = claim.ToPagedList(1, _appSettings.PageSize);
            return View("Index", Operations);
        }

        public IActionResult OperationEntry(string obj)
        {
            ClaimSearchobj claimSearchobj = Helpers.Deserilize<ClaimSearchobj>(Helpers.Decryption(obj));
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                Id = Convert.ToInt32(claimSearchobj.ClaimId),
                ClaimantId= claimSearchobj.ClaimantId

            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaimsMaster,
                Request = mainSearchMC
            };
            var claim = Helpers.ExcutePostAPI<List<ClaimMaster>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");
            ViewData["query"] = query;
            ViewData["obj"] = obj;
            ViewData["DocumentsLink"] = _appSettings.DocumentsLink;
            
            return View(claim.FirstOrDefault());
        }
        public IActionResult OperationAssign(int ClaimId,int ClaimantId)
        {
            ViewData["DivName"] = "OperationAssign";
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                ClaimantId = ClaimantId

            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaimsMaster,
                Request = mainSearchMC
            };
            var claim = Helpers.ExcutePostAPI<List<ClaimMaster>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");

            ViewData["AllUsers"] = HttpContext.Session.getSessionData<List<Users>>("AllUsers");
            return View("_SurveyorAssign", claim.FirstOrDefault());
        }
        public IActionResult UpdateReserve(int ClaimId,int  ClaimantId)
        {
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                Id = ClaimId,
                ClaimantId=ClaimantId
            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaimsMaster,
                Request = mainSearchMC
            };
            var claim = Helpers.ExcutePostAPI<List<ClaimMaster>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");
            return View("_UpdateReserve", claim.FirstOrDefault());
        }  
        
        public IActionResult OperationReOpen(int ClaimId, int ClaimantId)
        {
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                Id = ClaimId,
                ClaimantId = ClaimantId
            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaimsMaster,
                Request = mainSearchMC
            };
            var claim = Helpers.ExcutePostAPI<List<ClaimMaster>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");
            return View("_OperationReOpen", claim.FirstOrDefault());
        }
        public IActionResult UpdateRecovery(int ClaimId,int? ClaimantId=null)
        {
            MainSearchMC mainSearchMC = new MainSearchMC()
            {
                Id = ClaimId,
                ClaimantId= ClaimantId
            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaimsMaster,
                Request = mainSearchMC
            };
            var claim = Helpers.ExcutePostAPI<List<ClaimMaster>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");
            return View("_UpdateRecovery", claim.FirstOrDefault());
        }

        [HttpPost]
        public IActionResult ReOpenClaim()
        {
            int ClaimId = Convert.ToInt32(HttpContext.Request.Form["ClaimId"]);
            int? ClaimantID = HttpContext.Request.Form["ClaimantID"]==""?null: Convert.ToInt32(HttpContext.Request.Form["ClaimantID"]);
            string Reason = HttpContext.Request.Form["Note"];
            string Language = HttpContext.Session.getSessionData<string>("Lang").ToUpper();
            

                MainSearchMC mainSearchMC = new MainSearchMC()
                {
                    Id = ClaimId,
                    ClaimantId = ClaimantID,
                };
                SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
                {
                    TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaim,
                    Request = mainSearchMC
                };
              var  claims = Helpers.ExcutePostAPI<List<Claims>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");

            Claims claim = new Claims();
            claim = claims.FirstOrDefault();
            //claim.ClaimStatus = (int)Enums.ClaimStatus.ReOpen;

             setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.InsertUpdateClaim,
                Request = claim
            };
            claim = Helpers.ExcutePostAPI<Claims>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");

            Helpers.RegisterHistory(_appSettings, claim.Id, Reason, HttpContext.Session.getSessionData<Users>("LoggedUser").UserName,1);
            Helpers.SendNotificationMail(Language, _appSettings, _appSettings.OperationEmail, claim.ClaimNo);

            return View("_OperationReOpen", claim);
        }      
        
        
        [HttpPost]
        public IActionResult UpdateAssign()
        {
            int ClaimId = Convert.ToInt32(HttpContext.Request.Form["ClaimId"]);
            int ClaimantId = Convert.ToInt32(HttpContext.Request.Form["ClaimantId"]);
            int Validation = Convert.ToInt32(HttpContext.Request.Form["Validation"]);
            string Language = HttpContext.Session.getSessionData<string>("Lang").ToUpper();

MotorClaims/Views/Operations/OperationEntry.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http.Features
@using System.Globalization

@inject IViewLocalizer _localizer
@using CORE.DTOs.MotorClaim.Claims;
@model ClaimMaster
@{
    List<LookupTable> lookupTables = (List<LookupTable>)ViewData["query"];
    string obj=(string)ViewData["obj"];
    string DocumentsLink=(string)ViewData["DocumentsLink"];
    await Html.RenderPartialAsync("_PolicyInfo",Model.productionInfo);
    await Html.RenderPartialAsync("_VehicleInfo", Model.vehiclesInfo);
    await Html.RenderPartialAsync("_ClaimInfo", Model.claims);
    await Html.RenderPartialAsync("_ClaimantInfo",new { Model = Model.claimants,Lookups = lookupTables});
    await Html.RenderPartialAsync("_DocumentsInfo",new { Model = Model.attachments, Link = DocumentsLink,ClaimNo=string.Concat(Model.claims.ClaimNo,"/",Model.claimants.Serial),Documents=Model.documentInfos});
    await Html.RenderPartialAsync("_ClaimsHistory", Model.claimHistories);
}

<form id="frmClaimEntry" method="post" asp-controller="Operations">
    <input type="hidden" form="frmClaimEntry" name="Id" value="@Model.claims.Id" />
    <input type="hidden" form="frmClaimEntry" name="ClaimantId" value="@Model.claimants.Id" />
    <input type="hidden" form="frmClaimEntry" name="obj" value="@obj" />

    <div class="add-member-detail" style="max-width:100% !important">

        <div class="tabs-wrapper">
            <ul class="tabs-navigation-wrap">
                <li class="tab-navigation tab-custom-two active" id="tabTwoOne" onclick="selectTabsTwo('tabTwoOne','one_1'); ">
                    <div class="tab-item-text">
                        <a href="#">@_localizer["Operationentry"].Value </a>
                    </div>
                </li>
            </ul>
            <div class="tabbs-content-wrapper">
                <div class="tab-items-container tabs-one-content-two active" id="one_1">
                    <div class="member-summary-container">
                        <div class="total-member-list">
                            <div class="member-list-container">

                                <div class="member-collapse">
                                    <div class="member-collapse-header" style="display:block">
                                        <div class="vehicle-owner-grid">
                                            <label for="radio-card-v2-11" class="radio-card-v2" style="min-width:30% !important">
                                                <input required type="radio" value="@((int)MotorClaims.Models.Enums.ClaimantStatus.Operation)" name="ClaimStatus" id="radio-card-v2-11" @(Model.claimants.Id == 0 ? "checked" : (Model.claimants.ClaimantStatus == (int)MotorClaims.Models.Enums.ClaimantStatus.Operation ? "checked" : "")) />
                                                <div class="card-content-wrapper">
                                                    <span class="check-icon"></span>
                                                    <div class="card-content">
                                                        <h4 class="title">@(MotorClaims.Models.Enums.ClaimantStatus.Operation)</h4>
                                                    </div>
                                                </div>
                                            </label>
                                            <!-- /.radio-card -->

                                            <label for="radio-card-v2-12" class="radio-card-v2" style="min-width:30% !important">
                                                <input type="radio" value="@((int)MotorClaims.Models.Enums.ClaimantStatus.Rejected)" name="ClaimStatus" id="radio-card-v2-12" @(Model.claimants.ClaimantStatus == (int)MotorClaims.Models.Enums.ClaimantStatus.Rejected ? "checked" : "") />
                                                <div class="card-content-wrapper">
                                                    <span class="check-icon"></span>
                                                    <div class="card-content">
                                                        <h4 class="title">@(MotorClaims.Models.Enums.ClaimantStatus.Rejected)</h4>
                                                    </div>
                                                </div>
                                            </label>

                                    
                                        </div>
                                      
                                          <div class="vehicle-owner-grid">
                                            <span class="label">@_localizer["RejectionReason"].Value </span>
                                           <textarea name="RejectionReason" rows="7" id="txtRejectionReason" class="form-inputbox" maxlength="1024"></textarea>

                                    
                                        </div>

                                      
                                       
                                    </div>
                                 
                                </div>

                                
                        <div class="footer-actions-handle" style="position:inherit !important; width:100%">
          <div class="next-button" style="margin-right:5px">

                                        <button type="submit" asp-action="UpdateClaimStatus" class="button button-primary">
                                            @_localizer["Save"].Value
                                    
                                </button>
        
                              
                        

                        </div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
            
            </div>
        </div>

    </div>
</form>

                  <script>

             

                        $('input:radio[name="ClaimStatus"]').change(function() {
        if ($(this).val() == '@((int)MotorClaims.Models.Enums.ClaimantStatus.Rejected)') {     
              $('#txtRejectionReason').prop('required', true);
              $('#txtRejectionReason').show();

        } else {

              $('#txtRejectionReason').prop('required', false);
              $('#txtRejectionReason').hide();
        }
    });
                  </script>

MotorClaims/Views/Operations/eClaims.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http.Features
@using System.Globalization

@inject IViewLocalizer _localizer
@using CORE.DTOs.APIs.MotorClaim;
@using CORE.DTOs.MotorClaim;
@using Newtonsoft.Json;
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    eClaimsObj searchObj = (eClaimsObj)ViewData["eClaims"];
}
@model IPagedList<eClaims>

<div class="add-member-detail">
    <div class="policy-wrapper">
        <div class="basic-detail" style="background:none !important">
            <h2 class="heading">
                @_localizer["eClaims"].Value
                
            </h2>
            <div class="search-member">
                <form method="post" asp-action="SearcheClaims" asp-controller="Operations" style="display:flow-root">
      

                    <div class="search-filter-wrapper">


                      

                        <div class="search-wrapper">
                            <span class="label">
                                @_localizer["RegisteredFrom"].Value
                                
                            </span>
                            <div class="search-input-box-wrapper">

                                <div class="search-icon-wrapper">
                                    <img src="/assets/icons/calendar.svg" class="search-icon" alt="">
                                </div>
                                <input class="input-box" autocomplete="off" id="txtFrom" name="RegisteredFrom" type="text" value="@(searchObj.RegisteredFrom.HasValue?searchObj.RegisteredFrom.Value.ToString("dd-MM.yyyy"):"")">
                            </div>
                        </div>


                        <div class="search-wrapper">
                            <span class="label">
                                @_localizer["RegisteredTo"].Value
                                
                            </span>
                            <div class="search-input-box-wrapper">

                                <div class="search-icon-wrapper">
                                    <img src="/assets/icons/calendar.svg" class="search-icon" alt="">
                                </div>
                                <input class="input-box" autocomplete="off" id="txtTo" name="RegisteredTo" type="text" value="@(searchObj.RegisteredTo.HasValue?searchObj.RegisteredTo.Value.ToString("dd-MM.yyyy"):"")">
                            </div>
                        </div>

                    </div>
                    <div class="search-heading-wrap" style="float: right;margin-top: 10px;">

                        <button class="button button-secondary" type="submit">
                            @_localizer["Search"].Value
                            
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    @if (Model != null && Model.Count > 0)
    {
        <div class="policy-members">
            <div class="heading-card">
                <h2 class="heading">
                    @_localizer["eClaimsResult"].Value
                    
                </h2>
            </div>
            <div class="transaction-details">
                <table class="universal-table">
                    <tr>
                        <th>
                            @_localizer["AccidentReport"].Value
                            
                        </th>
                        <th>
                            @_localizer["SequenceNumber"].Value
                            
                        </th>
                        <th>
                            @_localizer["TaqdeerNumber"].Value
                            
                        </th>
                        <th>
                            @_localizer["OwnerNationalID"].Value
                            
                        </th>

                    </tr>


                    @foreach (var clm in Model)
                    {

                        <tr>
                            <td class="tran"><a href="">@clm.AccidentReport</a></td>

                            <td>@clm.SequenceNumber</td>
                            <td>@clm.TaqdeerNumber</td>
                            <td>@clm.OwnerNationalID</td>

                        </tr>


                    }
                </table>
                    @Html.PagedListPager((IPagedList)Model,Page=>Url.Action("Index","Managing",new {Page}))
                  Showing @Model.FirstItemOnPage to @Model.LastItemOnPage of @Model.TotalItemCount eClaims
            </div>
        </div>
    }
    else
    {
        <div class="ui-state-highlight ui-corner-all" style="background:none !important;margin-top: 1%;">
            <span class="ui-icon ui-icon-info" style="float: left"></span>
            <span>
                @_localizer["Noresultsfound"].Value
                .
            </span>
        </div>
    }
</div>
<div class="aside-right">
    <div class="inner-wrapper">
        <div class="vehicle-item">
            <div class="vehicle-header">
                <img src="/assets/motor/motor.svg" class="vehicle-icon" />
                <div class="vehicle-info">
                    <span class="vehicle-name">vehicle.Vehicle.MakeDesc vehicle.Vehicle.ModelDesc / vehicle.Vehicle.SequanceNo vehicle.Vehicle.CustomNo</span>
                    <span class="vehicle-no" style="text-transform:uppercase">
                        @_localizer["Plate Number:"].Value
                         vehicle.Vehicle.PlateNo
                    </span>
                </div>
            </div>
            <div class="vehicle-basic-body">
                <ul class="detail-list">
                    <li class="detailed-item">
                        <span class="detailed-icon-wrap">
                            <img src="/assets/icons/save.svg" alt="" class="item-icon">
                        </span>
                        <div class="item-content">
                            <span class="label">
                                @_localizer["PolicyNo"].Value
                                
                            </span>
                            <h3 class="value">policy.policy.PolicyNumber</h3>
                        </div>
                    </li>
                    <li class="detailed-item">
                        <span class="detailed-icon-wrap">
                            <img src="/assets/icons/calendar.svg" alt="" class="item-icon">
                        </span>
                        <div class="item-content">
                            <span class="label">
                                @_localizer["EffectiveDate"].Value
                                
                            </span>
                            <h3 class="value">HelpersDate.FormatDateNoTime(policy.policy.PolicyEffectiveDate)</h3>
                        </div>
                    </li>
                    <li class="detailed-item">
                        <span class="detailed-icon-wrap">
                            <img src="/assets/icons/calendar.svg" alt="" class="item-icon">
                        </span>
                        <div class="item-content">
                            <span class="label">
                                @_localizer["YearofManufacturing"].Value
                                
                            </span>
                            <h3 class="value">vehicle.Vehicle.ManufactureYear</h3>
                        </div>
                    </li>
                    <li class="detailed-item">
                        <span class="detailed-icon-wrap">
                            <img src="/assets/icons/calendar.svg" alt="" class="item-icon">
                        </span>
                        <div class="item-content">
                            <span class="label">
                                @_localizer["ExpiryDate"].Value
                                
                            </span>
                            <h3 class="value">HelpersDate.FormatDateNoTime(policy.policy.PolicyExpiryDate)</h3>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="common-slide-popup" id="UpdateReserve"></div>
<div class="common-slide-popup" id="UpdateRecovery"></div>
<div class="edit-member-id-popup" id="OperationAssign"></div>
<script>
    $('#txtFrom').ForceDateEntry();
    $('#txtTo').ForceDateEntry();
</script>