MotorClaims/Controllers/ClaimsController.cs
using CORE.DTOs.APIs.Authenticator;
using CORE.DTOs.APIs.Business;
using CORE.DTOs.APIs.MotorClaim;
using CORE.DTOs.APIs.Process.Payments;
using CORE.DTOs.APIs.Setups.MMP;
using CORE.DTOs.Authentications;
using CORE.DTOs.MotorClaim;
using CORE.DTOs.MotorClaim.Claims;
using CORE.DTOs.MotorClaim.Integrations.APIs;
using CORE.DTOs.MotorClaim.WorkFlow;
using CORE.DTOs.Setups;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using MotorClaims.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Net.Mail;
using System.Reflection;
using System.Security.Claims;
using System.Security.Principal;

namespace MotorClaims.Controllers
{
    public class ClaimsController : Controller
    {
        private static HttpClient client = new HttpClient();
        private readonly AppSettings _appSettings;
        private const string LookupTable = "LookupTable";
        private readonly IMemoryCache _memoryCache;
        public static IWebHostEnvironment _environment;
        List<LookupTable> query = new List<LookupTable>();

        public ClaimsController(IOptions<AppSettings> appSettings, IWebHostEnvironment environment, IMemoryCache memoryCache)
        {
            _environment = environment;
            _appSettings = appSettings.Value;
            _memoryCache = memoryCache;
            _memoryCache.TryGetValue(LookupTable, out query);
        }
        public IActionResult Index(string obj)
        {
            ClaimSearchobj claimSearchobj = Helpers.Deserilize<ClaimSearchobj>(Helpers.Decryption(obj));
            ClaimSearchResult claimSearchResult = HttpContext.Session.getSessionData<ClaimSearchResult>("SearchResult");
            Production policy = claimSearchResult.Productions.Where(p => p.policy.Id == claimSearchobj.PolicyId).FirstOrDefault();
            var Vehicle = policy?.Vehicles.Where(p => p.Vehicle.Id == claimSearchobj.VehicleId).FirstOrDefault();
            ViewData["Policy"] = policy;
            ViewData["Vehicle"] = Vehicle;
            return View();
        }

        public IActionResult ClaimEntry(string obj)
        {
            ClaimSearchobj claimSearchobj = Helpers.Deserilize<ClaimSearchobj>(Helpers.Decryption(obj));
            ClaimSearchResult claimSearchResult = HttpContext.Session.getSessionData<ClaimSearchResult>("SearchResult");
            var policy = claimSearchResult.Productions.Where(p => p.policy.Id == claimSearchobj.PolicyId).FirstOrDefault();
            var Vehicle = policy.Vehicles.Where(p => p.Vehicle.Id == claimSearchobj.VehicleId).FirstOrDefault();
            Claims claims = new Claims();
            if (claimSearchobj.ClaimId.HasValue && claimSearchobj.ClaimId.Value > 0)
            {
                MainSearchMC mainSearchMC = new MainSearchMC()
                {
                    Id = Convert.ToInt32(claimSearchobj.ClaimId.Value)
                };
                SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
                {
                    TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaim,
                    Request = mainSearchMC
                };
                var claim = Helpers.ExcutePostAPI<List<Claims>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");
                claims = claim.FirstOrDefault();
            }
            //Dictionary<string,string> keyValuePairs = new Dictionary<string,string>();
            //keyValuePairs.Add("ClaimNo", claims.ClaimNo);
            //keyValuePairs.Add("PlateNo", claims.PlateNo);
            //Helpers.SendSMSTemplate(2, keyValuePairs, "+966592032990", _appSettings);

          
            ViewData["Policy"] = policy;
            ViewData["Vehicle"] = Vehicle;
            ViewData["Cities"] = HttpContext.Session.getSessionData<List<LookupTable>>("Cities");
            return View(claims);
        }

        public IActionResult ClaimantDetails(string obj)
        {
            ViewData["Error"] = string.Empty;
            ClaimSearchResult claimSearchResult = HttpContext.Session.getSessionData<ClaimSearchResult>("SearchResult");
            Production policy = HttpContext.Session.getSessionData<Production>("policy");
            VehicleInfos Vehicle = HttpContext.Session.getSessionData<VehicleInfos>("Vehicle");
            Claimants claimants = new Claimants();
            claimants = HttpContext.Session.getSessionData<Claimants>("claimants");
            ViewData["ClaimantType"] = query.Where(p => p.MajorCode == (int)SystemEnums.ClaimantType).ToList();
            ViewData["DamageType"] = query.Where(p => p.MajorCode == (int)MotorClaims.Models.Enums.Lookups.DamageType).ToList();
            ViewData["Policy"] = policy;
            ViewData["Vehicle"] = Vehicle;
            ViewData["ClaimantResult"] = query.Where(p => p.MajorCode == (int)SystemEnums.ClaimantResult).ToList();

            return View("_ClaimantDetails", claimants);
        }
        public IActionResult ClaimantsEntry(string obj)
        {
            ViewData["Error"] = string.Empty;
            ClaimSearchobj claimSearchobj = Helpers.Deserilize<ClaimSearchobj>(Helpers.Decryption(obj));
            ClaimSearchResult claimSearchResult = HttpContext.Session.getSessionData<ClaimSearchResult>("SearchResult");
            var policy = claimSearchResult.Productions.Where(p => p.policy.Id == claimSearchobj.PolicyId).FirstOrDefault();
            var Vehicle = policy.Vehicles.Where(p => p.Vehicle.Id == claimSearchobj.VehicleId).FirstOrDefault();
            Claimants claimants = new Claimants();
            claimants.ClaimId = claimSearchobj.ClaimId.Value;
            if (claimSearchobj.ClaimId.HasValue && claimSearchobj.ClaimId.Value > 0)
            {
                MainSearchMC mainSearchMC = new MainSearchMC()
                {
                    ClaimId = Convert.ToInt32(claimSearchobj.ClaimId.Value)
                };
                SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
                {
                    TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaimants,
                    Request = mainSearchMC
                };
                var claimant = Helpers.ExcutePostAPI<List<Claimants>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");
                claimants = claimant != null && claimant.Count > 0 && claimSearchobj.ClaimantId.HasValue && claimSearchobj.ClaimantId.Value > 0 ? claimant.Where(p => p.Id == claimSearchobj.ClaimantId.Value).FirstOrDefault() : claimants;
            }
            ViewData["ClaimantType"] = query.Where(p => p.MajorCode == (int)SystemEnums.ClaimantType).ToList();
            ViewData["DamageType"] = query.Where(p => p.MajorCode == (int)MotorClaims.Models.Enums.Lookups.DamageType).ToList();
            ViewData["Policy"] = policy;
            ViewData["Vehicle"] = Vehicle;
            ViewData["obj"] = obj;
            claimants.ClaimantStatus = claimants.ClaimantStatus.HasValue ? claimants.ClaimantStatus.Value : (int)Enums.ClaimantStatus.Operation;
            HttpContext.Session.SetSessionData("claimants", claimants);
            HttpContext.Session.SetSessionData("policy", policy);
            HttpContext.Session.SetSessionData("Vehicle", Vehicle);
            ViewData["ClaimantResult"] = query.Where(p => p.MajorCode == (int)SystemEnums.ClaimantResult).ToList();

            return View("_ClaimantsEntry", claimants);
        }

        [HttpPost]
        public IActionResult InsertClaim(Claims claim)
        {

            int _min = 1000;
            int _max = 9999;
            Random _rdm = new Random();
            int otpPick = _rdm.Next(_min, _max);
            int PolicyId = Convert.ToInt32(HttpContext.Request.Form["PolicyId"].ToString().Split(",")[0]);
            int VehicleId = Convert.ToInt32(HttpContext.Request.Form["VehicleId"].ToString().Split(",")[0]);
            ClaimSearchResult claimSearchResult = HttpContext.Session.getSessionData<ClaimSearchResult>("SearchResult");
            List<Claims> claims = new List<Claims>();
            if (claim.ClaimReportType == (int)Models.Enums.ClaimReportType.Manual)
            {
                int ManualReportType = Convert.ToInt32(HttpContext.Request.Form["ManualReportType"]);
                string ReportNo = HttpContext.Request.Form["ReportNo"];
                if (ManualReportType == (int)Models.Enums.ClaimReportType.Najm)
                {
                    claim.AccidentNo = ReportNo;
                }
                else
                {
                    claim.BasherNo = ReportNo;
                }
            }
            MainSearchMC main = new MainSearchMC()
            {
                AccidentNo = claim.AccidentNo
            };
            SetupClaimsRequestcs setupClaimsRequestcs = new SetupClaimsRequestcs()
            {
                TransactionType = CORE.Extensions.ClaimTransactionType.LoadClaim,
                Request = main
            };
            var policy = claimSearchResult.Productions.Where(p => p.policy.Id == PolicyId).FirstOrDefault();
            var Vehicle = policy.Vehicles.Where(p => p.Vehicle.Id == VehicleId).FirstOrDefault();
            claims = Helpers.ExcutePostAPI<List<Claims>>(setupClaimsRequestcs, _appSettings.APIHubPrefix + "api/MotorClaim/ClaimsTransactions");
            ViewData["Policy"] = policy;
            ViewData["Vehicle"] = Vehicle;
            ViewData["Cities"] = HttpContext.Session.getSessionData<List<LookupTable>>("Cities");

            if (claims.Count > 0)
            {
                ViewData["Error"] = "This Accident No " + claim.AccidentNo + " already exist";
                claim = claims.FirstOrDefault();
                return View("ClaimEntry", claim);
            }

MotorClaims/Views/Claims/ClaimManagment.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http.Features
@using System.Globalization

@inject IViewLocalizer _localizer
@using CORE.DTOs.APIs.MotorClaim;
@using CORE.DTOs.MotorClaim;
@using CORE.DTOs.MotorClaim.Claims;
@using Newtonsoft.Json;
@{
    Production policy = (Production)ViewData["Policy"];
    VehicleInfos vehicle = (VehicleInfos)ViewData["Vehicle"];
    Claims claims = (Claims)ViewData["claims"];
    List<LookupTable> dClaimantType = (List<LookupTable>)ViewData["ClaimantType"];
    List<LookupTable> dClaimantResult = (List<LookupTable>)ViewData["ClaimantResult"];
    ClaimSearchobj claimSearchobj = new ClaimSearchobj();
}

@model List<Claimants>
<div class="policy-detail-wrapper">
    <div class="search-member">
        <div class="search-heading-wrap">
            <div class="heading-card">
                <h2 class="heading">
                    @_localizer["Khallad"].Value
                    ClaimsList
                </h2>
            </div>

        </div>

    </div>

</div>

<div class="transaction-details">
    <table class="universal-table">
        <tr>
            <!-- <th>#</th> -->
            <th>
                @_localizer["ClaimSegment"].Value
                
            </th>
            <th>
                @_localizer["PolicyType"].Value
                
            </th>
            <th>
                @_localizer["PolicyNumber"].Value
                
            </th>
            <th>
                @_localizer["Make"].Value
                
            </th>
            <th>
                @_localizer["Model"].Value
                
            </th>
            <th>
                @_localizer["Chassis"].Value
                
            </th>
            <th>
                @_localizer["CreationDate"].Value
                
            </th>
            <th>
                @_localizer["ClaimStatus"].Value
                
            </th>

        </tr>

        <tr>
            @{
                claimSearchobj = new ClaimSearchobj()
            {
                PolicyId = policy.policy.Id,
                VehicleId = vehicle.Vehicle.Id,
                ClaimId = claims.Id
            };

       
            }
            <td class="tran"><a href="@Url.Action("ClaimEntry","Claims",new{obj=MotorClaims.Models.Helpers.Encrypt(JsonConvert.SerializeObject(claimSearchobj))})">#@claims.ClaimNo</a></td>
            <td>@policy.policy.PolicyTypeName</td>
            <td>@policy.policy.PolicyNumber</td>
            <td>@vehicle.Vehicle.MakeDesc</td>
            <td>@vehicle.Vehicle.ModelDesc</td>
            <td>@vehicle.Vehicle.ChassisNo</td>
            <td>@HelpersDate.FormatDateNoTime(claims.CreationDate.Value)</td>
            @{
                var y = Enum.TryParse(claims.ClaimStatus.ToString(), out MotorClaims.Models.Enums.ClaimStatus parsedEnumValue);
            }
            <td>@parsedEnumValue</td>
        </tr>



    </table>
</div>
<div class="policy-detail-wrapper">
    <div class="search-member">
        <div class="search-heading-wrap">
            <div class="heading-card">
                <h2 class="heading">
                    @_localizer["ClaimantsList"].Value
                    
                </h2>
            </div>
            @{
                claimSearchobj = new ClaimSearchobj()
            {
                PolicyId = policy.policy.Id,
                VehicleId = vehicle.Vehicle.Id,
                ClaimId=claims.Id
            };
            }
            <a class="button button-secondary" href="@Url.Action("ClaimantsEntry","Claims",new{obj=MotorClaims.Models.Helpers.Encrypt(JsonConvert.SerializeObject(claimSearchobj))})">Add Claimant</a>

        </div>

    </div>

</div>


<div class="transaction-details">
    <table class="universal-table">
        <tr>
            <!-- <th>#</th> -->
            <th>
                @_localizer["ClaimantType"].Value
                
            </th>
            <th>
                @_localizer["ClaimantName"].Value
                
            </th>
            <th>
                @_localizer["LossType"].Value
                
            </th>
            <th>
                @_localizer["Make"].Value
                
            </th>
            <th>
                @_localizer["Model"].Value
                
            </th>
            <th>
                @_localizer["Chassis"].Value
                
            </th>
            <th>
                @_localizer["PlateNo"].Value
                
            </th>
            <th>
                @_localizer["ClaimantStatus"].Value
                
            </th>

        </tr>


        @foreach (var clm in Model)
        {

            <tr>
                @{
                    claimSearchobj = new ClaimSearchobj()
                {
                    PolicyId = policy.policy.Id,
                    VehicleId = vehicle.Vehicle.Id,
                    ClaimId = clm.ClaimId,
                    ClaimantId = clm.Id
                };
                    string ClaimantType = dClaimantType.Where(p => p.Code == clm.ClaimantType.Value.ToString()).FirstOrDefault().NameEnglish;
                    string ClaimantResult = dClaimantResult.Where(p => p.Code == clm.DamageType.Value.ToString()).FirstOrDefault().NameEnglish;
                }
                <td class="tran"><a href="@Url.Action("ClaimantsEntry","Claims",new{obj=MotorClaims.Models.Helpers.Encrypt(JsonConvert.SerializeObject(claimSearchobj))})">#@ClaimantType</a></td>
                <td>@ClaimantResult</td>
                <td></td>
                <td>@clm.MakeDesc</td>
                <td>@clm.ModelDesc</td>
                <td>@clm.ChassisNo</td>
                <td>@clm.PlateNo</td>
                <td>Open</td>

            </tr>


        }
    </table>
</div>

MotorClaims/Views/Claims/DocumentsUpload.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http.Features
@using System.Globalization

@inject IViewLocalizer _localizer
@using CORE.DTOs.MotorClaim.Claims;
@using CORE.DTOs.MotorClaim.WorkFlow;
@using Newtonsoft.Json;

@model ClaimMaster
@{
    Layout = null;
    int VehicleId = (int)ViewData["VehicleId"];
    int PolicyId = (int)ViewData["PolicyId"];
    int ModuleId = (int)ViewData["ModuleId"];
    int? ClaimId = (int?)ViewData["ClaimId"];
    int? ClaimantId = (int?)ViewData["ClaimantId"];
    string? Link = (string?)ViewData["Link"];
    List<DocumentInfo> documentInfos = (List<DocumentInfo>)ViewData["documentInfos"];
}
@if (documentInfos != null && documentInfos.Count > 0)
{
    <div class="transaction-details">
        <table class="universal-table">
            <tr>
                <!-- <th>#</th> -->
                <th>
                    @_localizer["DocumentName"].Value
                    
                </th>
                <th>
                    @_localizer["ModuleName"].Value
                    
                </th>
                <th>
                    @_localizer["DocumentType"].Value
                    
                </th>
                <th>
                    @_localizer["Status"].Value
                    
                </th>
                <th>
                    @_localizer["Action"].Value
                    
                </th>
            </tr>


            @foreach (var doc in documentInfos)
            {

                <tr>
                    @{
                        ClaimSearchobj claimSearchobj = new ClaimSearchobj()
                    {
                        PolicyId = PolicyId,
                        VehicleId = VehicleId,
                        ClaimId = ClaimId.HasValue ? ClaimId.Value : 0,
                        ClaimantId = ClaimantId.HasValue ? ClaimantId.Value : 0
                    };
                    }

                    @if (Model.attachments.Any(p => p.DocumentSetupId == doc.Id))
                    {
                        <td class="tran">
                            <a target="_blank" href="@(Link+ Model.attachments.Where(p=>p.DocumentSetupId==doc.Id).FirstOrDefault().FileName)">@doc.Name</a>
                        </td>

                    }
                    else
                    {
                        <td>
                            <span>@doc.Name</span>
                        </td>
                    }
                    <td>@(ClaimId.HasValue ? MotorClaims.Models.Enums.DocumnetType.Claim : MotorClaims.Models.Enums.DocumnetType.Claimant)</td>
                    <td>
                        @if (doc.IsRequired)
                        {
                            <span>
                                @_localizer["Required"].Value
                                
                            </span>
                        }
                        else
                        {
                            <span>
                                @_localizer["Optional"].Value
                                
                            </span>
                        }
                    </td>
                    <td>
                        @if (Model.attachments.Any(p => p.DocumentSetupId == doc.Id))
                        {
                            <span>
                                @_localizer["Uploaded"].Value
                                
                            </span>
                        }
                        else
                        {
                            <span>
                                @_localizer["Missing"].Value
                                
                            </span>
                        }
                    </td>
                    <td>
                        @*<form id="frmUploadDocument@(++i)" method="post" asp-action="UploadAttachments" asp-controller="Claims">*@
                        <input type="hidden" name="ModuleId" value="@ModuleId" />
                        <input type="hidden" name="PolicyId" value="@PolicyId" />
                        <input type="hidden" name="VehicleId" value="@VehicleId" />
                        <input type="hidden" name="ClaimId" value="@ClaimId" />
                        <input type="hidden" name="ClaimantId" value="@ClaimantId" />
                        <div class="ducument-detaild-Attachment">
                            <label for="fromFiles@(doc.Id)" class="document-card">
                                <img src="/assets/icons/upload.svg" class="docuemet-icon" alt="">

                                @if (Model.attachments.Any(p => p.DocumentSetupId == doc.Id))
                                {
                                    <p id="Attachment@(doc.Id)" class="document-tile-text">@Model.attachments.Where(p=>p.DocumentSetupId==doc.Id).FirstOrDefault().FileName</p>
                                }
                                else
                                {
                                    <p id="Attachment@(doc.Id)" class="document-tile-text"> Upload Attachment</p>
                                }
                                <input onchange="Upload(@doc.Id,@(ClaimId.HasValue?ClaimId.Value:0),@ModuleId,@ClaimantId,@Model.attachments.Where(p=>p.DocumentSetupId==doc.Id).FirstOrDefault().Id,@Model.claimants.Serial)" accept="image/png, image/gif, image/jpeg,application/pdf" class="ducument-control" id="fromFiles@(doc.Id)" name="fromFiles" type="file" />
                            </label>

                        </div>
                        @*</form>*@
                    </td>
                </tr>


            }
        </table>
    </div>
}
else
{
    <div class="ui-state-highlight ui-corner-all" style="background:none !important;margin-top: 1%;">
        <span class="ui-icon ui-icon-info" style="float: left"></span>
        <span>
            @_localizer["Noresultsfound"].Value
            
        </span>
    </div>
}

<script>
    @*    $(function(){
        document.getElementById("fromFiles1").onchange = function () {
        document.getElementById("frmMedicalReupload").submit();
        };
        });*@
        function Upload(Id, ClaimId, ModuleId, ClaimantId,attachId,Serial) {

    @*        const input = document.getElementById('fromFiles' + Id)
                var $formdata = new FormData();
                input.addEventListener('change', (event) => {
                const target = event.target
                if (target.files && target.files[0]) {
                $('#Attachment' + Id).text(target.files[0].name);
                $formdata.append(target.files[0].name, input.files[0]);
                document.getElementById("frmUploadDocument" + Id).submit();
                }

                });*@
                        const input = document.getElementById('fromFiles' + Id)
            var files = input.files;
            var $formdata = new FormData();

            for (var i = 0; i != files.length; i++) {
                $formdata.append("files", files[i]);
            }

            $.ajax(
                {
                    url: "/Claims/UploadAttachments/?Id=" + Id + "&ClaimId=" + ClaimId + "&ModuleId=" + ModuleId + "&ClaimantId=" + ClaimantId+"&attachId="+attachId+"&Serial="+Serial,
                    data: $formdata,
                    processData: false,
                    contentType: false,
                    type: "POST",
                    success: function (data) {
                        $('#Attachment' + Id).text($formdata.get("files").name);
                    }
                }
            );

        }

</script>

MotorClaims/Views/Claims/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Http.Features
@using System.Globalization

@inject IViewLocalizer _localizer
@using CORE.DTOs.APIs.MotorClaim;
@using CORE.DTOs.MotorClaim;
@using Newtonsoft.Json;
@{
    Production policy = (Production)ViewData["Policy"];
    VehicleInfos vehicle = (VehicleInfos)ViewData["Vehicle"];
}


<div class="policy-detail-wrapper">


    @{
        await Html.RenderPartialAsync("_PolicyInfo", policy.policy);
    }

    @{
        await Html.RenderPartialAsync("_VehicleInfo", vehicle.Vehicle);
    }

    @*   @{
    await Html.RenderPartialAsync("_ClaimInfo", vehicle);
    }
    @{
    await Html.RenderPartialAsync("_ClaimantInfo", vehicle);
    }*@




    <div class="search-member">
        <div class="search-heading-wrap">
            <div class="heading-card">
                <h2 class="heading">
                    @_localizer["ClaimsList"].Value
                    
                </h2>
            </div>
            @{
                ClaimSearchobj claimSearchobj = new ClaimSearchobj()
            {
                PolicyId = policy.policy.Id,
                VehicleId = vehicle.Vehicle.Id
            };
            }
            <a class="button button-secondary" href="@Url.Action("ClaimEntry","Claims",new{obj=MotorClaims.Models.Helpers.Encrypt(JsonConvert.SerializeObject(claimSearchobj))})">Add Claim</a>

        </div>

    </div>

</div>
@if (vehicle.lsClaims.Count > 0)
{
    <div class="transaction-details">
        <table class="universal-table">
            <tr>
                <!-- <th>#</th> -->
                <th>
                    @_localizer["ClaimSegment"].Value
                    
                </th>
                <th>
                    @_localizer["PolicyType"].Value
                    
                </th>
                <th>
                    @_localizer["PolicyNumber"].Value
                    
                </th>
                <th>
                    @_localizer["Make"].Value
                    
                </th>
                <th>
                    @_localizer["Model"].Value
                    
                </th>
                <th>
                    @_localizer["Chassis"].Value
                    
                </th>
                <th>
                    @_localizer["CreationDate"].Value
                    
                </th>
                <th>
                    @_localizer["ClaimStatus"].Value
                    
                </th>

            </tr>


            @foreach (var clm in vehicle.lsClaims)
            {

                <tr>
                    @{
                        claimSearchobj = new ClaimSearchobj()
                    {
                        PolicyId = policy.policy.Id,
                        VehicleId = vehicle.Vehicle.Id,
                        ClaimId = clm.Id
                    };
                    }
                    <td class="tran"><a href="@Url.Action("ClaimManagment","Claims",new{obj=MotorClaims.Models.Helpers.Encrypt(JsonConvert.SerializeObject(claimSearchobj))})">#@clm.ClaimNo</a></td>
                    <td>@policy.policy.PolicyTypeName</td>
                    <td>@policy.policy.PolicyNumber</td>
                    <td>@vehicle.Vehicle.MakeDesc</td>
                    <td>@vehicle.Vehicle.ModelDesc</td>
                    <td>@vehicle.Vehicle.ChassisNo</td>
                    <td>@HelpersDate.FormatDateNoTime(clm.CreationDate.Value)</td>
                    @{
                        var y = Enum.TryParse(clm.ClaimStatus.ToString(), out MotorClaims.Models.Enums.ClaimStatus parsedEnumValue);
                    }
                    <td>@parsedEnumValue</td>

                </tr>


            }
        </table>
    </div>
}
else
{
    <div class="ui-state-highlight ui-corner-all" style="background:none !important;margin-top: 1%;">
        <span class="ui-icon ui-icon-info" style="float: left"></span>
        <span>
            @_localizer["Noresultsfound"].Value
            .
        </span>
    </div>
}





<!-- cancel policy driver no -->